### PR TITLE
fix: support Node.js 10.x

### LINKED ISSUE #5: Node.js 10.x support
I've looking for localhost detecting library and found this library.
`is-localhost-ip` is exactly the library that I was looking for.

Howevery, `is-localhost-ip` require Node.js 12>= (`Array#flatMap` and `dns.promises`)
I want to support Node.js 10.x because Node.js 12 is not [LTS](https://github.com/nodejs/Release) yet.

If you ok, I want to submit Pull Request.

```diff
diff --git a/index.js b/index.js
index 3cc9233..a03bd9b 100644
--- a/index.js
+++ b/index.js
@@ -1,13 +1,15 @@
 'use strict';
 
 const { isIP } = require('net');
-const { lookup } = require('dns').promises;
+const { lookup } = require('dns');
 const { networkInterfaces } = require('os');
 
+
+
 const INTERFACES_ADDRESSES = new Set(
-  Object.values(networkInterfaces()).flatMap(arr =>
-    arr.map(({ address }) => address)
-  )
+  Object.values(networkInterfaces()).reduce((arr, networkInterface) =>
+      arr.concat(networkInterface.map(({ address }) => address))
+  , [])
 );
 
 const IP_RANGES = [
@@ -47,19 +49,22 @@ async function isLocalhost(ip) {
   }
 
   // it's a DNS name
-  try {
-    const addresses = await lookup(ip, { all: true });
-    return (
-      Array.isArray(addresses) &&
-      addresses.some(
-        ({ address }) =>
-          IP_RANGES.some(it => it.test(address)) ||
-          INTERFACES_ADDRESSES.has(address)
-      )
-    );
-  } catch (err) {
-    return false;
-  }
+  return new Promise((resolve) => {
+    lookup(ip, {all: true}, (error, addresses) => {
+      if (error) {
+        return resolve(false);
+      }
+      const isLocalhost = (
+          Array.isArray(addresses) &&
+          addresses.some(
+              ({ address }) =>
+                  IP_RANGES.some(it => it.test(address)) ||
+                  INTERFACES_ADDRESSES.has(address)
+          )
+      );
+      resolve(isLocalhost);
+    });
+  });
 }
 
 module.exports = isLocalhost;
```

### PR DESCRIPTION
**Pull request by azu**
Feel free to merge it.

- use `Array#reduce` instead of `Array#flatMap`
- use callback version of dns lookup

fix #5

### CODE REVIEW

**Comment by tinovyatkin** [comment]
@azu `dns.promises` were added in 10.6 - is it still too high version for you? I can agree to drop flatMap, but DNS promisifying looks weird...

**Comment by azu** [comment]
@tinovyatkin `dns.promises` is experimental feature on Node.js 10.
Node.js 10 always show warning message.

> (node:98400) ExperimentalWarning: The dns.promises API is experimental

I want to avoid this.

**Comment by tinovyatkin** [comment]
Well, it _was_ experimental. Now from Node 12.x we know that it will stay and become LTS later this year. Do you prefer bunch of promisifying code over native code and warning?

**Comment by tinovyatkin** [comment]
@azu Let's do compromise? 10.6 without promisifying `dns` and `flatMap`? 😉

**Comment by azu** [comment]
In my experience, ExperimentalWarning in a library is not good.
ExperimentalWarning make user cofuse.

- [ExperimentalWarning: The fs.promises API is experimental (Node.js 10.1.0) · Issue #577 · jprichardson/node-fs-extra](https://github.com/jprichardson/node-fs-extra/issues/577)
- [ExperimentalWarning: The fs.promises API is experimental · Issue #1178 · pnpm/pnpm](https://github.com/pnpm/pnpm/issues/1178)

I want to avoid half support.
Support or Drop.

**Comment by azu** [comment]
>  If you agree just add here `engines` correction at `package.json` and `README` fix mentioning 12.x

OK!
I've updated engined and README!

**Pull request merged**
